Update version specifier
jarondl/pygtfs pull request #72
Opened 2023-05-10 05:18 UTC by fabaff

Fixes:

```bash
error in pygtfs setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
    pytz>=2012d
```

2023-05-15 16:39 UTC, jimbudarz commented
Interesting- it looks like there was a [prerelease for pytz](https://pypi.org/project/pytz/2012d/).
I don't see "2012" in pypi, though.

2023-05-24 12:38 UTC, jimbudarz requested changes
I think pytz needs to be bumped to 2014.9

2023-05-24 12:38 UTC, jimbudarz commented on setup.py
> +                      'pytz>=2012',
I ran into errors with any versions prior to `pytz 2014.9`. Would tou please bump this dependency to `'pytz>=2014.9',`?

2023-07-14 17:36 UTC, jarondl commented
Obsoleted by #76.

2023-07-14 17:36 UTC, closed without merging